import { StyleSheet } from 'react-native';
 
const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F7F8FB' },
  header: { paddingHorizontal: 20, paddingTop: 20 },
  headerInner: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  backButton: {
    backgroundColor: 'transparent',
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoWrapper: {
    backgroundColor: '#051A2F',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: { width: 40, height: 40, borderRadius: 12 },
  headerCenter: { alignItems: 'center', flex: 1 },
  headerTitle: { fontSize: 20, fontWeight: '600', color: '#262A4F' },
  subTitle: { fontSize: 12, color: '#8C91C1' },
  logoutButton: { padding: 4 },
  logoutIcon: { width: 30, height: 20 },
  scrollArea: { marginTop: 20 },
  topBanner: {
    backgroundColor: '#262A4F',
    borderRadius: 16,
    padding: 18,
    alignItems: 'center',
    marginHorizontal: 20,
  },
  topBannerText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  topBannerSub: { color: '#E5E7FF', fontSize: 13, marginTop: 4 },
  highlight: { color: '#FFD700' },
  knowMore: { color: '#61AFFE', fontSize: 13 },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    margin: 20,
    padding: 16,
    borderRadius: 16,
    elevation: 2,
  },
  profileAvatar: { width: 64, height: 64, borderRadius: 32, marginRight: 12 },
  profileText: { flex: 1 },
  profileName: { fontSize: 16, fontWeight: '600', color: '#262A4F' },
  profileDetails: { fontSize: 13, color: '#8C91C1', marginTop: 2 },
  twoCards: { flexDirection: 'row', justifyContent: 'space-between', marginHorizontal: 20 },
  bigCard: {
    backgroundColor: '#fff',
    flex: 0.48,
    borderRadius: 16,
    padding: 16,
    elevation: 2,
  },
  bigCardTitle: { fontSize: 15, fontWeight: '600', color: '#262A4F', marginTop: 8 },
  bigCardSub: { color: '#8C91C1', fontSize: 13, marginTop: 4 },
  rechargeBtn: {
    backgroundColor: '#262A4F',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginTop: 10,
  },
  bigRechargeText: { color: '#fff', textAlign: 'center', fontSize: 13 },
  bigAccentLink: { color: '#61AFFE', fontSize: 13, marginTop: 6 },
  storyBanner: {
    backgroundColor: '#fff',
    borderRadius: 16,
    margin: 20,
    padding: 16,
    alignItems: 'center',
    elevation: 2,
  },
  storyText: { fontSize: 15, fontWeight: '600', color: '#262A4F' },
  socialRow: { flexDirection: 'row', marginTop: 12, gap: 12 },
  socialIcon: {
    backgroundColor: '#262A4F',
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsCard: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'space-between',
    elevation: 2,
  },
  settingsTitle: { fontSize: 15, fontWeight: '600', color: '#262A4F' },
  rewardsCard: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    marginHorizontal: 20,
    alignItems: 'center',
    elevation: 2,
  },
  rewardsText: { marginLeft: 10, fontSize: 15, color: '#262A4F', fontWeight: '500' },
  logoutCard: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    marginHorizontal: 20,
    alignItems: 'center',
    elevation: 2,
  },
  logoutText: { marginLeft: 10, fontSize: 15, color: '#262A4F', fontWeight: '500' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.45)' },
  modalContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
    elevation: 20,
    maxHeight: '80%',
  },
  profileImageContainer: { alignItems: 'center', marginBottom: 10 },
  profileImage: { width: 120, height: 120, borderRadius: 60, marginBottom: 8 },
  imageButtonRow: { flexDirection: 'row', gap: 8 },
  addImageButton: {
    backgroundColor: '#262A4F',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  addImageText: { color: '#fff', fontWeight: '600' },
  deleteImageButton: {
    backgroundColor: '#ccc',
    paddingVertical: 6,
    paddingHorizontal: 14,
    borderRadius: 8,
  },
  deleteImageText: { color: '#000', fontWeight: '600' },
  detailBox: {
    backgroundColor: '#f5f6fa',
    borderRadius: 12,
    padding: 10,
    marginTop: 8,
  },
 
  // FIXED: Long text (Address) wraps properly
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  detailLabel: {
    fontWeight: '600',
    color: '#262A4F',
    flex: 0.4,
  },
  detailValueContainer: {
    flex: 0.6,
    flexShrink: 1,
  },
  detailValue: {
    color: '#333',
    flexShrink: 1,
    textAlign: 'right',
  },
 
  // ADDED: These were missing → caused TS errors
  editButton: {
    marginTop: 14,
    backgroundColor: '#262A4F',
    paddingVertical: 10,
    borderRadius: 10,
    alignItems: 'center',
  },
  editButtonText: { color: '#fff', fontWeight: '700' },
 
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(255,255,255,0.7)',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
 
export default styles;
 